/**
 * File generated by Magnet rest2mobile 1.1 - 23/11/2017 12:43:45 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import java.util.List;

public interface GW2API {

  /**
   * Generated from URL GET https://api.guildwars2.com/v2/characters?access_token=
   * GET v2/characters
   * @param access_token  style:QUERY
   * @param listener
   * @return List<java.lang.String>
   */
  Call<List<java.lang.String>> getCharacterNames(
     String access_token,
     StateChangedListener listener
  );


}
