/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "name" : "RaekarWolfpaw",
  "race" : "Norn",
  "gender" : "Male",
  "profession" : "Ranger",
  "level" : 80,
  "guild" : "D78B8CC9-7307-457F-A250-AD5B17BB857B",
  "age" : 136087,
  "created" : "2015-07-06T12:21:00Z",
  "deaths" : 16,
  "crafting" : [ {
    "discipline" : "Huntsman",
    "rating" : 3,
    "active" : true
  } ],
  "title" : 209,
  "backstory" : [ "25-119", "26-123", "183-181", "27-125", "7-53" ],
  "wvw_abilities" : [ {
    "id" : 25,
    "rank" : 1
   ...

 */

public class AllCharactersResult {

  
  private Integer age;

  
  private List<java.lang.String> backstory;

  
  private List<Bag> bags;

  
  private List<Crafting> crafting;

  
  private String created;

  
  private Integer deaths;

  
  private List<Equipment> equipment;

  
  private String gender;

  
  private String guild;

  
  private Integer level;

  
  private String name;

  
  private String profession;

  
  private String race;

  
  private List<java.lang.Integer> recipes;

  
  private Skills skills;

  
  private Specializations specializations;

  
  private Integer title;

  
  private List<Training> training;

  
  private List<Wvw_ability> wvw_abilities;

  public Integer getAge() {
    return age;
  }
  public List<java.lang.String> getBackstory() {
    return backstory;
  }
  public List<Bag> getBags() {
    return bags;
  }
  public List<Crafting> getCrafting() {
    return crafting;
  }
  public String getCreated() {
    return created;
  }
  public Integer getDeaths() {
    return deaths;
  }
  public List<Equipment> getEquipment() {
    return equipment;
  }
  public String getGender() {
    return gender;
  }
  public String getGuild() {
    return guild;
  }
  public Integer getLevel() {
    return level;
  }
  public String getName() {
    return name;
  }
  public String getProfession() {
    return profession;
  }
  public String getRace() {
    return race;
  }
  public List<java.lang.Integer> getRecipes() {
    return recipes;
  }
  public Skills getSkills() {
    return skills;
  }
  public Specializations getSpecializations() {
    return specializations;
  }
  public Integer getTitle() {
    return title;
  }
  public List<Training> getTraining() {
    return training;
  }
  public List<Wvw_ability> getWvw_abilities() {
    return wvw_abilities;
  }

  /**
  * Builder for AllCharactersResult
  **/
  public static class AllCharactersResultBuilder {
    private AllCharactersResult toBuild = new AllCharactersResult();

    public AllCharactersResultBuilder() {
    }

    public AllCharactersResult build() {
      return toBuild;
    }

    public AllCharactersResultBuilder age(Integer value) {
      toBuild.age = value;
      return this;
    }
    public AllCharactersResultBuilder backstory(List<java.lang.String> value) {
      toBuild.backstory = value;
      return this;
    }
    public AllCharactersResultBuilder bags(List<Bag> value) {
      toBuild.bags = value;
      return this;
    }
    public AllCharactersResultBuilder crafting(List<Crafting> value) {
      toBuild.crafting = value;
      return this;
    }
    public AllCharactersResultBuilder created(String value) {
      toBuild.created = value;
      return this;
    }
    public AllCharactersResultBuilder deaths(Integer value) {
      toBuild.deaths = value;
      return this;
    }
    public AllCharactersResultBuilder equipment(List<Equipment> value) {
      toBuild.equipment = value;
      return this;
    }
    public AllCharactersResultBuilder gender(String value) {
      toBuild.gender = value;
      return this;
    }
    public AllCharactersResultBuilder guild(String value) {
      toBuild.guild = value;
      return this;
    }
    public AllCharactersResultBuilder level(Integer value) {
      toBuild.level = value;
      return this;
    }
    public AllCharactersResultBuilder name(String value) {
      toBuild.name = value;
      return this;
    }
    public AllCharactersResultBuilder profession(String value) {
      toBuild.profession = value;
      return this;
    }
    public AllCharactersResultBuilder race(String value) {
      toBuild.race = value;
      return this;
    }
    public AllCharactersResultBuilder recipes(List<java.lang.Integer> value) {
      toBuild.recipes = value;
      return this;
    }
    public AllCharactersResultBuilder skills(Skills value) {
      toBuild.skills = value;
      return this;
    }
    public AllCharactersResultBuilder specializations(Specializations value) {
      toBuild.specializations = value;
      return this;
    }
    public AllCharactersResultBuilder title(Integer value) {
      toBuild.title = value;
      return this;
    }
    public AllCharactersResultBuilder training(List<Training> value) {
      toBuild.training = value;
      return this;
    }
    public AllCharactersResultBuilder wvw_abilities(List<Wvw_ability> value) {
      toBuild.wvw_abilities = value;
      return this;
    }
  }
}
