/**
 * File generated by Magnet rest2mobile 1.1 - 24/11/2017 4:35:46 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "id" : 9448,
  "size" : 15,
  "inventory" : [ {
    "id" : 23045,
    "count" : 1,
    "charges" : 37,
    "binding" : "Account"
  }, {
    "id" : 66961,
    "count" : 1,
    "binding" : "Character",
    "bound_to" : "Lazeen"
  }, {
    "id" : 17320,
    "count" : 1,
    "skin" : 4266,
    "upgrades" : [ 24618 ],
    "binding" : "Character",
    "bound_to" : "Lazeen"
   ...

 */

public class Bag {

  
  private Integer id;

  
  private List<Inventory> inventory;

  
  private Integer size;

  public Integer getId() {
    return id;
  }
  public List<Inventory> getInventory() {
    return inventory;
  }
  public Integer getSize() {
    return size;
  }

  /**
  * Builder for Bag
  **/
  public static class BagBuilder {
    private Bag toBuild = new Bag();

    public BagBuilder() {
    }

    public Bag build() {
      return toBuild;
    }

    public BagBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public BagBuilder inventory(List<Inventory> value) {
      toBuild.inventory = value;
      return this;
    }
    public BagBuilder size(Integer value) {
      toBuild.size = value;
      return this;
    }
  }
}
