/**
 * File generated by Magnet rest2mobile 1.1 - 24/11/2017 4:35:46 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "name" : "Lazeen",
  "race" : "Asura",
  "gender" : "Male",
  "flags" : [ "Beta" ],
  "profession" : "Mesmer",
  "level" : 80,
  "guild" : "D78B8CC9-7307-457F-A250-AD5B17BB857B",
  "age" : 1812355,
  "created" : "2012-08-25T15:05:00Z",
  "deaths" : 393,
  "crafting" : [ {
    "discipline" : "Artificer",
    "rating" : 81,
    "active" : true
  }, {
    "discipline" : "Jeweler",
    "rating" : 400,
    "active" : true
  }, {
      ...

 */

public class CharacterByNameResult {

  
  private Integer age;

  
  private List<java.lang.String> backstory;

  
  private List<Bag> bags;

  
  private List<Crafting> crafting;

  
  private String created;

  
  private Integer deaths;

  
  private List<Equipment> equipment;

  
  private List<java.lang.String> flags;

  
  private String gender;

  
  private String guild;

  
  private Integer level;

  
  private String name;

  
  private String profession;

  
  private String race;

  
  private List<java.lang.Integer> recipes;

  
  private Skills skills;

  
  private Specializations specializations;

  
  private Integer title;

  
  private List<Training> training;

  public Integer getAge() {
    return age;
  }
  public List<java.lang.String> getBackstory() {
    return backstory;
  }
  public List<Bag> getBags() {
    return bags;
  }
  public List<Crafting> getCrafting() {
    return crafting;
  }
  public String getCreated() {
    return created;
  }
  public Integer getDeaths() {
    return deaths;
  }
  public List<Equipment> getEquipment() {
    return equipment;
  }
  public List<java.lang.String> getFlags() {
    return flags;
  }
  public String getGender() {
    return gender;
  }
  public String getGuild() {
    return guild;
  }
  public Integer getLevel() {
    return level;
  }
  public String getName() {
    return name;
  }
  public String getProfession() {
    return profession;
  }
  public String getRace() {
    return race;
  }
  public List<java.lang.Integer> getRecipes() {
    return recipes;
  }
  public Skills getSkills() {
    return skills;
  }
  public Specializations getSpecializations() {
    return specializations;
  }
  public Integer getTitle() {
    return title;
  }
  public List<Training> getTraining() {
    return training;
  }

  /**
  * Builder for CharacterByNameResult
  **/
  public static class CharacterByNameResultBuilder {
    private CharacterByNameResult toBuild = new CharacterByNameResult();

    public CharacterByNameResultBuilder() {
    }

    public CharacterByNameResult build() {
      return toBuild;
    }

    public CharacterByNameResultBuilder age(Integer value) {
      toBuild.age = value;
      return this;
    }
    public CharacterByNameResultBuilder backstory(List<java.lang.String> value) {
      toBuild.backstory = value;
      return this;
    }
    public CharacterByNameResultBuilder bags(List<Bag> value) {
      toBuild.bags = value;
      return this;
    }
    public CharacterByNameResultBuilder crafting(List<Crafting> value) {
      toBuild.crafting = value;
      return this;
    }
    public CharacterByNameResultBuilder created(String value) {
      toBuild.created = value;
      return this;
    }
    public CharacterByNameResultBuilder deaths(Integer value) {
      toBuild.deaths = value;
      return this;
    }
    public CharacterByNameResultBuilder equipment(List<Equipment> value) {
      toBuild.equipment = value;
      return this;
    }
    public CharacterByNameResultBuilder flags(List<java.lang.String> value) {
      toBuild.flags = value;
      return this;
    }
    public CharacterByNameResultBuilder gender(String value) {
      toBuild.gender = value;
      return this;
    }
    public CharacterByNameResultBuilder guild(String value) {
      toBuild.guild = value;
      return this;
    }
    public CharacterByNameResultBuilder level(Integer value) {
      toBuild.level = value;
      return this;
    }
    public CharacterByNameResultBuilder name(String value) {
      toBuild.name = value;
      return this;
    }
    public CharacterByNameResultBuilder profession(String value) {
      toBuild.profession = value;
      return this;
    }
    public CharacterByNameResultBuilder race(String value) {
      toBuild.race = value;
      return this;
    }
    public CharacterByNameResultBuilder recipes(List<java.lang.Integer> value) {
      toBuild.recipes = value;
      return this;
    }
    public CharacterByNameResultBuilder skills(Skills value) {
      toBuild.skills = value;
      return this;
    }
    public CharacterByNameResultBuilder specializations(Specializations value) {
      toBuild.specializations = value;
      return this;
    }
    public CharacterByNameResultBuilder title(Integer value) {
      toBuild.title = value;
      return this;
    }
    public CharacterByNameResultBuilder training(List<Training> value) {
      toBuild.training = value;
      return this;
    }
  }
}
