/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "id" : 19699,
  "count" : 7
}

 */

public class Item {

  
  private Integer count;

  
  private Integer id;

  public Integer getCount() {
    return count;
  }
  public Integer getId() {
    return id;
  }

  /**
  * Builder for Item
  **/
  public static class ItemBuilder {
    private Item toBuild = new Item();

    public ItemBuilder() {
    }

    public Item build() {
      return toBuild;
    }

    public ItemBuilder count(Integer value) {
      toBuild.count = value;
      return this;
    }
    public ItemBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
  }
}
