/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "id" : 4590265113,
  "item_id" : 25149,
  "price" : 3962,
  "quantity" : 1,
  "created" : "2017-04-15T05:23:28+00:00",
  "purchased" : "2017-11-20T23:37:02+00:00"
}

 */

public class PastSalesResult {

  
  private String created;

  
  private Long id;

  
  private Integer item_id;

  
  private Integer price;

  
  private String purchased;

  
  private Integer quantity;

  public String getCreated() {
    return created;
  }
  public Long getId() {
    return id;
  }
  public Integer getItem_id() {
    return item_id;
  }
  public Integer getPrice() {
    return price;
  }
  public String getPurchased() {
    return purchased;
  }
  public Integer getQuantity() {
    return quantity;
  }

  /**
  * Builder for PastSalesResult
  **/
  public static class PastSalesResultBuilder {
    private PastSalesResult toBuild = new PastSalesResult();

    public PastSalesResultBuilder() {
    }

    public PastSalesResult build() {
      return toBuild;
    }

    public PastSalesResultBuilder created(String value) {
      toBuild.created = value;
      return this;
    }
    public PastSalesResultBuilder id(Long value) {
      toBuild.id = value;
      return this;
    }
    public PastSalesResultBuilder item_id(Integer value) {
      toBuild.item_id = value;
      return this;
    }
    public PastSalesResultBuilder price(Integer value) {
      toBuild.price = value;
      return this;
    }
    public PastSalesResultBuilder purchased(String value) {
      toBuild.purchased = value;
      return this;
    }
    public PastSalesResultBuilder quantity(Integer value) {
      toBuild.quantity = value;
      return this;
    }
  }
}
