/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "terrestrial" : [ 51, 45 ],
  "aquatic" : [ 45, 19 ]
}

 */

public class Pets {

  
  private List<java.lang.Integer> aquatic;

  
  private List<java.lang.Integer> terrestrial;

  public List<java.lang.Integer> getAquatic() {
    return aquatic;
  }
  public List<java.lang.Integer> getTerrestrial() {
    return terrestrial;
  }

  /**
  * Builder for Pets
  **/
  public static class PetsBuilder {
    private Pets toBuild = new Pets();

    public PetsBuilder() {
    }

    public Pets build() {
      return toBuild;
    }

    public PetsBuilder aquatic(List<java.lang.Integer> value) {
      toBuild.aquatic = value;
      return this;
    }
    public PetsBuilder terrestrial(List<java.lang.Integer> value) {
      toBuild.terrestrial = value;
      return this;
    }
  }
}
