/**
 * File generated by Magnet rest2mobile 1.1 - 27/11/2017 4:11:17 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "id" : 10,
  "traits" : [ 682, 713, 680 ]
}

 */

public class Pve {

  
  private Integer id;

  
  private List<java.lang.Integer> traits;

  public Integer getId() {
    return id;
  }
  public List<java.lang.Integer> getTraits() {
    return traits;
  }

  /**
  * Builder for Pve
  **/
  public static class PveBuilder {
    private Pve toBuild = new Pve();

    public PveBuilder() {
    }

    public Pve build() {
      return toBuild;
    }

    public PveBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public PveBuilder traits(List<java.lang.Integer> value) {
      toBuild.traits = value;
      return this;
    }
  }
}
