/**
 * File generated by Magnet rest2mobile 1.1 - 24/11/2017 4:35:46 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "id" : 1,
  "traits" : [ 701, 1960, 1950 ]
}

 */

public class Pvp {

  
  private Integer id;

  
  private List<java.lang.Integer> traits;

  public Integer getId() {
    return id;
  }
  public List<java.lang.Integer> getTraits() {
    return traits;
  }

  /**
  * Builder for Pvp
  **/
  public static class PvpBuilder {
    private Pvp toBuild = new Pvp();

    public PvpBuilder() {
    }

    public Pvp build() {
      return toBuild;
    }

    public PvpBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public PvpBuilder traits(List<java.lang.Integer> value) {
      toBuild.traits = value;
      return this;
    }
  }
}
