/**
 * File generated by Magnet rest2mobile 1.1 - 24/11/2017 4:35:46 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "heal" : 21750,
  "utilities" : [ 30814, 29526, 10247 ],
  "elite" : 30359
}

 */

public class SkillsPve {

  
  private Integer elite;

  
  private Integer heal;

  
  private List<java.lang.Integer> utilities;

  public Integer getElite() {
    return elite;
  }
  public Integer getHeal() {
    return heal;
  }
  public List<java.lang.Integer> getUtilities() {
    return utilities;
  }

  /**
  * Builder for SkillsPve
  **/
  public static class SkillsPveBuilder {
    private SkillsPve toBuild = new SkillsPve();

    public SkillsPveBuilder() {
    }

    public SkillsPve build() {
      return toBuild;
    }

    public SkillsPveBuilder elite(Integer value) {
      toBuild.elite = value;
      return this;
    }
    public SkillsPveBuilder heal(Integer value) {
      toBuild.heal = value;
      return this;
    }
    public SkillsPveBuilder utilities(List<java.lang.Integer> value) {
      toBuild.utilities = value;
      return this;
    }
  }
}
