/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "heal" : 44948,
  "utilities" : [ 40498, 45970, 45789 ],
  "elite" : 45717,
  "pets" : {
    "terrestrial" : [ 51, 45 ],
    "aquatic" : [ 45, 19 ]
  }
}

 */

public class SkillsPve {

  
  private Integer elite;

  
  private Integer heal;

  
  private Pets pets;

  
  private List<java.lang.Integer> utilities;

  public Integer getElite() {
    return elite;
  }
  public Integer getHeal() {
    return heal;
  }
  public Pets getPets() {
    return pets;
  }
  public List<java.lang.Integer> getUtilities() {
    return utilities;
  }

  /**
  * Builder for SkillsPve
  **/
  public static class SkillsPveBuilder {
    private SkillsPve toBuild = new SkillsPve();

    public SkillsPveBuilder() {
    }

    public SkillsPve build() {
      return toBuild;
    }

    public SkillsPveBuilder elite(Integer value) {
      toBuild.elite = value;
      return this;
    }
    public SkillsPveBuilder heal(Integer value) {
      toBuild.heal = value;
      return this;
    }
    public SkillsPveBuilder pets(Pets value) {
      toBuild.pets = value;
      return this;
    }
    public SkillsPveBuilder utilities(List<java.lang.Integer> value) {
      toBuild.utilities = value;
      return this;
    }
  }
}
