/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "pve" : [ {
    "id" : 33,
    "traits" : [ 1099, 1101, 1701 ]
  }, {
    "id" : 30,
    "traits" : [ 1069, 1846, 1912 ]
  }, {
    "id" : 55,
    "traits" : [ 2071, 2161, 2128 ]
  } ]
}

 */

public class Specializations {

  
  private List<Pve> pve;

  public List<Pve> getPve() {
    return pve;
  }

  /**
  * Builder for Specializations
  **/
  public static class SpecializationsBuilder {
    private Specializations toBuild = new Specializations();

    public SpecializationsBuilder() {
    }

    public Specializations build() {
      return toBuild;
    }

    public SpecializationsBuilder pve(List<Pve> value) {
      toBuild.pve = value;
      return this;
    }
  }
}
