/**
 * File generated by Magnet rest2mobile 1.1 - 28/11/2017 4:10:12 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "id" : 161,
  "attributes" : {
    "Power" : 45,
    "Precision" : 32,
    "CritDamage" : 32
  }
}

 */

public class Stats {

  
  private Attributes attributes;

  
  private Integer id;

  public Attributes getAttributes() {
    return attributes;
  }
  public Integer getId() {
    return id;
  }

  /**
  * Builder for Stats
  **/
  public static class StatsBuilder {
    private Stats toBuild = new Stats();

    public StatsBuilder() {
    }

    public Stats build() {
      return toBuild;
    }

    public StatsBuilder attributes(Attributes value) {
      toBuild.attributes = value;
      return this;
    }
    public StatsBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
  }
}
