/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "id" : 1,
  "value" : 7460497
}

 */

public class WalletResult {

  
  private Integer id;

  
  private Integer value;

  public Integer getId() {
    return id;
  }
  public Integer getValue() {
    return value;
  }

  /**
  * Builder for WalletResult
  **/
  public static class WalletResultBuilder {
    private WalletResult toBuild = new WalletResult();

    public WalletResultBuilder() {
    }

    public WalletResult build() {
      return toBuild;
    }

    public WalletResultBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public WalletResultBuilder value(Integer value) {
      toBuild.value = value;
      return this;
    }
  }
}
