/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "id" : 10,
  "traits" : [ 682, 693, 680 ]
}

 */

public class Wvw {

  
  private Integer id;

  
  private List<java.lang.Integer> traits;

  public Integer getId() {
    return id;
  }
  public List<java.lang.Integer> getTraits() {
    return traits;
  }

  /**
  * Builder for Wvw
  **/
  public static class WvwBuilder {
    private Wvw toBuild = new Wvw();

    public WvwBuilder() {
    }

    public Wvw build() {
      return toBuild;
    }

    public WvwBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public WvwBuilder traits(List<java.lang.Integer> value) {
      toBuild.traits = value;
      return this;
    }
  }
}
