/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 3:57:04 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "attribute" : "Power",
  "modifier" : 85
}

 */

public class Attribute {

  
  private String attribute;

  
  private Integer modifier;

  public String getAttribute() {
    return attribute;
  }
  public Integer getModifier() {
    return modifier;
  }

  /**
  * Builder for Attribute
  **/
  public static class AttributeBuilder {
    private Attribute toBuild = new Attribute();

    public AttributeBuilder() {
    }

    public Attribute build() {
      return toBuild;
    }

    public AttributeBuilder attribute(String value) {
      toBuild.attribute = value;
      return this;
    }
    public AttributeBuilder modifier(Integer value) {
      toBuild.modifier = value;
      return this;
    }
  }
}
