/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "Power" : 45,
  "Precision" : 32,
  "CritDamage" : 32
}

 */

public class Attributes {

  
@com.google.gson.annotations.SerializedName("ConditionDamage")
  private Integer conditionDamage;

  
@com.google.gson.annotations.SerializedName("ConditionDuration")
  private Integer conditionDuration;

  
@com.google.gson.annotations.SerializedName("CritDamage")
  private Integer critDamage;

  
@com.google.gson.annotations.SerializedName("Power")
  private Integer power;

  
@com.google.gson.annotations.SerializedName("Precision")
  private Integer precision;

  public Integer getConditionDamage() {
    return conditionDamage;
  }
  public Integer getConditionDuration() {
    return conditionDuration;
  }
  public Integer getCritDamage() {
    return critDamage;
  }
  public Integer getPower() {
    return power;
  }
  public Integer getPrecision() {
    return precision;
  }

  /**
  * Builder for Attributes
  **/
  public static class AttributesBuilder {
    private Attributes toBuild = new Attributes();

    public AttributesBuilder() {
    }

    public Attributes build() {
      return toBuild;
    }

    public AttributesBuilder conditionDamage(Integer value) {
      toBuild.conditionDamage = value;
      return this;
    }
    public AttributesBuilder conditionDuration(Integer value) {
      toBuild.conditionDuration = value;
      return this;
    }
    public AttributesBuilder critDamage(Integer value) {
      toBuild.critDamage = value;
      return this;
    }
    public AttributesBuilder power(Integer value) {
      toBuild.power = value;
      return this;
    }
    public AttributesBuilder precision(Integer value) {
      toBuild.precision = value;
      return this;
    }
  }
}
