/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 3:57:04 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "id" : 1,
  "name" : "Coin",
  "description" : "TheprimarycurrencyofTyria.Spentatvendorsthroughouttheworld.",
  "order" : 110,
  "icon" : "https://render.guildwars2.com/file/98457F504BA2FAC8457F532C4B30EDC23929ACF9/619316.png"
}

 */

public class CurrencyByIdResult {

  
  private String description;

  
  private String icon;

  
  private Integer id;

  
  private String name;

  
  private Integer order;

  public String getDescription() {
    return description;
  }
  public String getIcon() {
    return icon;
  }
  public Integer getId() {
    return id;
  }
  public String getName() {
    return name;
  }
  public Integer getOrder() {
    return order;
  }

  /**
  * Builder for CurrencyByIdResult
  **/
  public static class CurrencyByIdResultBuilder {
    private CurrencyByIdResult toBuild = new CurrencyByIdResult();

    public CurrencyByIdResultBuilder() {
    }

    public CurrencyByIdResult build() {
      return toBuild;
    }

    public CurrencyByIdResultBuilder description(String value) {
      toBuild.description = value;
      return this;
    }
    public CurrencyByIdResultBuilder icon(String value) {
      toBuild.icon = value;
      return this;
    }
    public CurrencyByIdResultBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public CurrencyByIdResultBuilder name(String value) {
      toBuild.name = value;
      return this;
    }
    public CurrencyByIdResultBuilder order(Integer value) {
      toBuild.order = value;
      return this;
    }
  }
}
