/**
 * File generated by Magnet rest2mobile 1.1 - 27/11/2017 4:11:17 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "id" : 1917768093,
  "item_id" : 19699,
  "price" : 174,
  "quantity" : 7,
  "created" : "2017-11-27T05:09:26+00:00"
}

 */

public class CurrentBuysResult {

  
  private String created;

  
  private Integer id;

  
  private Integer item_id;

  
  private Integer price;

  
  private Integer quantity;

  public String getCreated() {
    return created;
  }
  public Integer getId() {
    return id;
  }
  public Integer getItem_id() {
    return item_id;
  }
  public Integer getPrice() {
    return price;
  }
  public Integer getQuantity() {
    return quantity;
  }

  /**
  * Builder for CurrentBuysResult
  **/
  public static class CurrentBuysResultBuilder {
    private CurrentBuysResult toBuild = new CurrentBuysResult();

    public CurrentBuysResultBuilder() {
    }

    public CurrentBuysResult build() {
      return toBuild;
    }

    public CurrentBuysResultBuilder created(String value) {
      toBuild.created = value;
      return this;
    }
    public CurrentBuysResultBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public CurrentBuysResultBuilder item_id(Integer value) {
      toBuild.item_id = value;
      return this;
    }
    public CurrentBuysResultBuilder price(Integer value) {
      toBuild.price = value;
      return this;
    }
    public CurrentBuysResultBuilder quantity(Integer value) {
      toBuild.quantity = value;
      return this;
    }
  }
}
