/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 3:57:04 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "id" : 4528348683,
  "item_id" : 24624,
  "price" : 22828,
  "quantity" : 1,
  "created" : "2017-10-17T07:22:34+00:00",
  "purchased" : "2017-10-17T07:24:05+00:00"
}

 */

public class PastBuysResult extends TradingResult {

  
//  private String created;
//
//
//  private Long id;
//
//
//  private Integer item_id;
//
//
//  private Integer price;
//
//
//  private String purchased;
//
//
//  private Integer quantity;
//
//  public String getCreated() {
//    return created;
//  }
//  public Long getId() {
//    return id;
//  }
//  public Integer getItem_id() {
//    return item_id;
//  }
//  public Integer getPrice() {
//    return price;
//  }
//  public String getPurchased() {
//    return purchased;
//  }
//  public Integer getQuantity() {
//    return quantity;
//  }

  /**
  * Builder for PastBuysResult
  **/
  public static class PastBuysResultBuilder {
    private PastBuysResult toBuild = new PastBuysResult();

    public PastBuysResultBuilder() {
    }

    public PastBuysResult build() {
      return toBuild;
    }

    public PastBuysResultBuilder created(String value) {
      toBuild.created = value;
      return this;
    }
    public PastBuysResultBuilder id(Long value) {
      toBuild.id = value;
      return this;
    }
    public PastBuysResultBuilder item_id(Integer value) {
      toBuild.item_id = value;
      return this;
    }
    public PastBuysResultBuilder price(Integer value) {
      toBuild.price = value;
      return this;
    }
    public PastBuysResultBuilder purchased(String value) {
      toBuild.purchased = value;
      return this;
    }
    public PastBuysResultBuilder quantity(Integer value) {
      toBuild.quantity = value;
      return this;
    }
  }
}
