/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "pve" : {
    "heal" : 44948,
    "utilities" : [ 40498, 45970, 45789 ],
    "elite" : 45717,
    "pets" : {
      "terrestrial" : [ 51, 45 ],
      "aquatic" : [ 45, 19 ]
    }
  }
}

 */

public class Skills {

  
  private SkillsPve pve;

  public SkillsPve getPve() {
    return pve;
  }

  /**
  * Builder for Skills
  **/
  public static class SkillsBuilder {
    private Skills toBuild = new Skills();

    public SkillsBuilder() {
    }

    public Skills build() {
      return toBuild;
    }

    public SkillsBuilder pve(SkillsPve value) {
      toBuild.pve = value;
      return this;
    }
  }
}
