/**
 * File generated by Magnet rest2mobile 1.1 - 24/11/2017 4:35:46 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "pve" : [ {
    "id" : 10,
    "traits" : [ 682, 713, 680 ]
  }, {
    "id" : 24,
    "traits" : [ 721, 722, 2035 ]
  }, {
    "id" : 40,
    "traits" : [ 1987, 1978, 1890 ]
  } ],
  "pvp" : [ {
    "id" : 1,
    "traits" : [ 701, 1960, 1950 ]
  }, {
    "id" : 45,
    "traits" : [ 675, 673, 671 ]
  }, {
    "id" : 23,
    "traits" : [ 756, 740, 1866 ]
   ...

 */

public class Specializations {

  
  private List<Pve> pve;

  
  private List<Pvp> pvp;

  
  private List<Wvw> wvw;

  public List<Pve> getPve() {
    return pve;
  }
  public List<Pvp> getPvp() {
    return pvp;
  }
  public List<Wvw> getWvw() {
    return wvw;
  }

  /**
  * Builder for Specializations
  **/
  public static class SpecializationsBuilder {
    private Specializations toBuild = new Specializations();

    public SpecializationsBuilder() {
    }

    public Specializations build() {
      return toBuild;
    }

    public SpecializationsBuilder pve(List<Pve> value) {
      toBuild.pve = value;
      return this;
    }
    public SpecializationsBuilder pvp(List<Pvp> value) {
      toBuild.pvp = value;
      return this;
    }
    public SpecializationsBuilder wvw(List<Wvw> value) {
      toBuild.wvw = value;
      return this;
    }
  }
}
