/**
 * File generated by Magnet rest2mobile 1.1 - 05/12/2017 4:34:52 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.luke.tyriadex.model.beans;


/**
 * Generated from json example
{
  "id" : 25,
  "rank" : 1
}

 */

public class Wvw_ability {

  
  private Integer id;

  
  private Integer rank;

  public Integer getId() {
    return id;
  }
  public Integer getRank() {
    return rank;
  }

  /**
  * Builder for Wvw_ability
  **/
  public static class Wvw_abilityBuilder {
    private Wvw_ability toBuild = new Wvw_ability();

    public Wvw_abilityBuilder() {
    }

    public Wvw_ability build() {
      return toBuild;
    }

    public Wvw_abilityBuilder id(Integer value) {
      toBuild.id = value;
      return this;
    }
    public Wvw_abilityBuilder rank(Integer value) {
      toBuild.rank = value;
      return this;
    }
  }
}
